import migrateRefreshTokens from './migrate-refresh_tokens';
import migrateOrganizations from './migrate-organizations';
import migrateRoles from './migrate-roles';
import migrateDepartments from './migrate-departments';
import migrateUsers from './migrate-users';
import migrateProjects from './migrate-projects';
import migrateAttendance from './migrate-attendance';
import migrateWorkSessions from './migrate-work_sessions';
import migratePayroll from './migrate-payroll';
import migratePayrollEntries from './migrate-payroll_entries';
import migratePerformanceReviews from './migrate-performance_reviews';
import migrateComplianceRules from './migrate-compliance_rules';
import migrateComplianceViolations from './migrate-compliance_violations';
import migrateProjectMembers from './migrate-project_members';
import migrateTasks from './migrate-tasks';
import migrateTaskComments from './migrate-task_comments';
import migrateTaskAttachments from './migrate-task_attachments';
import migrateGoals from './migrate-goals';
import migrateKpis from './migrate-kpis';
import migrateCourses from './migrate-courses';
import migrateCourseEnrollments from './migrate-course_enrollments';
import migrateWellnessLogs from './migrate-wellness_logs';
import migrateNotifications from './migrate-notifications';
import migrateActivityLogs from './migrate-activity_logs';

async function runMigrations() {
	await migrateOrganizations();
	await migrateRoles();
	await migrateDepartments();
	await migrateUsers();
	await migrateOrganizations();
	await migrateRoles();
	await migrateDepartments();
	await migrateUsers();
	await migrateRefreshTokens();
	await migrateProjects();
	await migrateAttendance();
	await migrateWorkSessions();
	await migratePayroll();
	await migratePayrollEntries();
	await migratePerformanceReviews();
	await migrateComplianceRules();
	await migrateComplianceViolations();
	await migrateProjectMembers();
	await migrateTasks();
	await migrateTaskComments();
	await migrateTaskAttachments();
	await migrateGoals();
	await migrateKpis();
	await migrateCourses();
	await migrateCourseEnrollments();
	await migrateWellnessLogs();
	await migrateNotifications();
	await migrateActivityLogs();
	console.log('All migrations completed successfully.');
}
runMigrations();
